Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoSZ.Context;
using Schutzens.Models;

namespace Schutzens.Controllers
{
    [Route("[controller]")]
    public class ProdutoController : Controller
    {
        private readonly SchutzenDbContext _db;

        public ProdutoController(SchutzenDbContext db)
        {
            _db = db;
        }

        

        public IActionResult Index()
        {
            IEnumerable<Produto> produtos = _db.Produtos;    
            return View(produtos);
            
        }
    }
}

Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoSZ.Context;
using ProjetoSZ.Models;

namespace Schutzens.Controllers
{
    [Route("[controller]")]
    public class ServicoController : Controller
    {

        private readonly SchutzenDbContext _db;
        public ServicoController(SchutzenDbContext db){
            _db = db;
        }
        
        
        public IActionResult Index()
        {
            List<Servico> objServicoList = _db.Servicos.ToList();
            return View(objServicoList);
        }

        

    }       
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoSZ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/produto.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoSZ.styles.css" asp-append-version="true" />
</head>
<body>
    <nav class="cabecalho">
            <img class="logo" src="~/img/logoNome.png" alt="">
                <ul class="list-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Servico" asp-action="Index">Serviços</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
    </nav>
    <hr>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjetoSZ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>