Models/CarrinhoCompra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ProjetoSZ.Context;

namespace Schutzens.Models
{
    public class CarrinhoCompra
    {
        private readonly SchutzenDbContext _context;
        public CarrinhoCompra(SchutzenDbContext context)
        {
            _context = context;
        }

        public string CarrinhoCompraId { get; set; }
        public List<CarrinhoCompraItem> CarrinhoCompraItens { get; set; }
        public static CarrinhoCompra GetCarrinho(IServiceProvider services){
            ISession session =
                services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<SchutzenDbContext>();

            string carrinhoId = session.GetString("CarrinhoId")?? Guid.NewGuid().ToString();

            session.SetString("CarrinhoId", carrinhoId);

            return new CarrinhoCompra(context)
            {
                CarrinhoCompraId = carrinhoId
            }    ;
        }

        public void AdicionarAoCarrinho(Produto produto)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
                i => i.Produto.ProdutoId == produto.ProdutoId &&
                i.CarrinhoCompraId == CarrinhoCompraId );

            if(carrinhoCompraItem == null)
            {
                carrinhoCompraItem = new CarrinhoCompraItem
                {
                    CarrinhoCompraId = CarrinhoCompraId,
                    Produto = produto,
                    Quantidade = 1
                };
                _context.CarrinhoCompraItens.Add(carrinhoCompraItem);
            }
            else
            {
                carrinhoCompraItem.Quantidade++;
            }
            _context.SaveChanges();    
        }

        public int RemoverDoCarrinho(Produto produto)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
                i => i.Produto.ProdutoId == produto.ProdutoId &&
                i.CarrinhoCompraId == CarrinhoCompraId);

            var quantidadeLocal = 0;

            if(carrinhoCompraItem.Quantidade>1)
            {
                carrinhoCompraItem.Quantidade--;
                quantidadeLocal = carrinhoCompraItem.Quantidade;
            }
            else
            {
                _context.CarrinhoCompraItens.Remove(carrinhoCompraItem);
            }

            _context.SaveChanges();
            return quantidadeLocal;
        }

        public List<CarrinhoCompraItem> GetCarrinhoCompraItens()
        {
            return CarrinhoCompraItens ??
            (CarrinhoCompraItens =
                _context.CarrinhoCompraItens.Where(c => c.CarrinhoCompraId == CarrinhoCompraId).Include(s => s.Produto).ToList());
        }

        public void LimparCarrinho()
        {
            var carrinhoItens = _context.CarrinhoCompraItens
                .Where(carrinho => carrinho.CarrinhoCompraId == CarrinhoCompraId);
                _context.CarrinhoCompraItens.RemoveRange(carrinhoItens);
                _context.SaveChanges();
        }

        public decimal GetCarrinhoCompraTotal()
        {
            var total = _context.CarrinhoCompraItens.Where(_c => _c.CarrinhoCompraId == CarrinhoCompraId)
                .Select(c => c.Produto.PrecoProduto * c.Quantidade).Sum();
            return total;
        }
    }
}

ViewModels/CarrinhoCompraViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Schutzens.Models;

namespace Schutzens.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra{ get; set; }
        public decimal CarrinhoCompraTotal { get; set; }
    }
}

Controllers/CarrinhoCompraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Schutzens.Models;
using Schutzens.Repositories.Interfaces;
using Schutzens.ViewModels;

namespace Schutzens.Controllers
{
    [Route("[controller]")]
    public class CarrinhoCompraController : Controller
    {
        private readonly IProdutoRepository _ProdutoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IProdutoRepository produtoRepository, CarrinhoCompra carrinhoCompra)
        {
            _ProdutoRepository = produtoRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal(),
            };
            return View(carrinhoCompraVM);
        }

        public RedirectToActionResult AdicionarItemNoCarrinhoDeCompra(int produtoId){
            var produtoSelecionado = _ProdutoRepository.produtos.FirstOrDefault(p => p.ProdutoId == produtoId);
            if (produtoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(produtoSelecionado);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoDeCompra(int produtoId){
            var produtoSelecionado = _ProdutoRepository.produtos
                                    .FirstOrDefault(p => p.ProdutoId == produtoId);
            
            if(produtoSelecionado != null){
                _carrinhoCompra.RemoverDoCarrinho(produtoSelecionado);
            }

            return RedirectToAction("Index");
        }

        
    }
}

Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoSZ.Context;
using Schutzens.Models;

namespace Schutzens.Controllers
{
    [Route("[controller]")]
    public class ProdutoController : Controller
    {
        private readonly SchutzenDbContext _db;

        public ProdutoController(SchutzenDbContext db)
        {
            _db = db;
        }

        

        public IActionResult Index()
        {
            IEnumerable<Produto> produtos = _db.Produtos;    
            return View(produtos);
            
        }
    }
}

Views/CarrinhoCompra/Index.cshtml
@using Schutzens.ViewModels
@model CarrinhoCompraViewModel

<div class="Container">
<div class="row checkoutForm">
      <img src="~/img/Full-Cart-icon.png" />
     <div>
       <h4> Seu carrinho de compras : </h4>
    </div>

    <table class="table table-bordered table-striped">

         <thead>
            <tr>
                <th>Quantidade</th>
                <th>Produto</th>
                <th class="text-right">Preço</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach(var item in Model.CarrinhoCompra.CarrinhoCompraItens)
            {
                  <tr>
                      <td class="text-center">@item.Quantidade</td>
                      <td class="text-left">@item.Produto.ProdutoNome</td>
                      <td class="text-right">@item.Produto.PrecoProduto.ToString("c")</td>
                      
                       <td class="text-right">
                          @((item.Quantidade * item.Produto.PrecoProduto).ToString("c"))
                       </td>

                       <td class="text-center">
                         <a asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinhoCompra" 
                          asp-route-lancheId="@item.Produto.ProdutoId"><img src="~/images/delete.png" width="10px" height="10px" />
                         </a>
                      </td>
                  </tr>                  
            }
        </tbody>
         <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.CarrinhoCompraTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    
    <div class="text-right">
        <div class="btn-group">
         <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
            &nbsp;&nbsp;&nbsp;
         <a class="btn btn-primary" asp-controller="Produto" asp-action="Index">Continuar Comprando</a>
        </div>
    </div>
   <br />
</div>
</div>